env:
  - RAILS_VERSION=3.2.15
  - RAILS_VERSION=3.2.15
  - RAILS_VERSION=3.2.19 USE_TURBOLINKS=true
  - RAILS_VERSION=4.0.8
  - RAILS_VERSION=4.1.4
  - RAILS_VERSION=4.1.4 USE_TURBOLINKS=true
  - RAILS_VERSION=4.2.4 
  - RAILS_VERSION=4.2.4 USE_TURBOLINKS=true
  - RAILS_VERSION=master
 
rvm:
 - 1.9.3
 - 2.0.0
 - jruby-19mode


matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
